import { HeaderNavigation } from "@/components/HeaderNavigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={inter.className}>
                <header className="hidden md:flex items-center py-2 px-4 gap-6 sticky top-0 border-b w-full z-50 bg-white">
                    <Link href="/">
                        <div className="flex items-center gap-4">
                            <div className="aspect-square border rounded-full h-12 w-12 flex items-center justify-center leading-none">
                                アイ
                                <br />
                                コン
                            </div>
                            <h1 className="font-extrabold text-lg break-words">
                                <span className="inline-block">京大</span>
                                <span className="inline-block">マーケティング</span>
                                <span className="inline-block">研究所</span>
                            </h1>
                        </div>
                    </Link>
                    <HeaderNavigation></HeaderNavigation>
                </header>
                <header className="flex md:hidden justify-center items-center py-2 px-4 gap-6 sticky top-0 border-b w-full z-50 bg-white">
                    <div className="absolute left-4 border rounded p-1 h-8 w-8 flex justify-center items-center justify-self-start">三</div>
                    <Link href="/">
                        <div className="flex items-center gap-4">
                            <div className="aspect-square border rounded-full h-12 w-12 flex items-center justify-center leading-none">
                                アイ
                                <br />
                                コン
                            </div>
                            <h1 className="font-extrabold text-lg break-words">
                                <span className="inline-block">京大</span>
                                <span className="inline-block">マーケ</span>
                            </h1>
                        </div>
                    </Link>
                </header>
                {children}
            </body>
        </html>
    );
}
